version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              make
      - restore_cache:
          keys:
            - {% raw %}v1-{{ .Branch }}{% endraw %}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build application Docker image
          command: |
            make package
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar {{cookiecutter.docker_hub_username}}/{{cookiecutter.app_name}}
      - save_cache:
          key:  {% raw %}v1-{{ .Branch }}-{{ epoch }}{% endraw %}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            make test # docker-compose -f ./docker-compose.test.yml up
      - run:
          name: Push application Docker image
          command: |
            make tag
            make push
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "deploy!"
            fi