app_name: user
docker_build_image_version: "1.11"
docker_hub_username: gofunct
docker_image: alpine
full_name: Coleman Word
github_username: gofunct
grpc_port: :9090
http_port: :8080
json_logs: "y"
log_level: debug
project_short_description: user description
viper_config_name: config
