app_name: cookiecutter.app_name
docker_build_image_version: cookiecutter.docker_build_image_version
docker_hub_username: cookiecutter.docker_hub_username
docker_image: cookiecutter.docker_image
full_name: cookiecutter.full_name
github_username: cookiecutter.github_username
grpc_port: cookiecutter.grpc_port
http_port: cookiecutter.http_port
json_logs: cookiecutter.json_logs
log_level: cookiecutter.log_level
project_short_description: cookiecutter.project_short_description
viper_config_name: cookiecutter.viper_config_name
